### ISSUE TITLE
Dockerfile in .dockerignore?

### ISSUE THREAD

**Issue by eterps** [blendle/docker-ruby#5]
Ik krijg:

```shell
docker build -t blendle/ruby:2.1.5 .
2015/04/28 19:42:57 Dockerfile was excluded by .dockerignore pattern 'Dockerfile'
```

Als ik de Dockerfile regel verwijder uit https://github.com/blendle/docker-ruby/blob/master/.dockerignore dan werkt het weer.

**Comment by JeanMertz** [comment]
@eterps welke versie van Docker gebruik je?

Deze error zou je niet moeten krijgen als je een recente versie gebruikt (voorgaande versies konden niet overweg met `Dockerfile` in de `.dockerignore`. De reden waarom dit nu wel kan, is zodat het aanpassen van je `Dockerfile` niet ervoor zorgt dat je hele "app" directory cache invalidated is, en die laag (en alle daaropvolgende lagen) opnieuw gebouwd moeten worden.

**Comment by eterps** [comment]
Ok, ik zal upgraden, ik gebruik 1.2.0 (die kwam mee op mijn Ubuntu)

**Comment by JeanMertz** [comment]
@eterps ah ja, deze feature werkt pas [sinds 1.5.0](https://github.com/docker/docker/blob/master/CHANGELOG.md#150-2015-02-10)
